export enum MessageType {
  LOGIN_REGISTER = "LOGIN_REGISTER",
  Logout = "LOGOUT",
  FetchData = "FETCH_DATA",
  SaveData = "SAVE_DATA",
  ERROR = "ERROR",
  INFO = "INFO",
  WARNING = "WARNING",
  DISABLE_BTN = "DISABLE_BTN",
  ENABLE_BTN = "ENABLE_BTN",
  REFRESH_EVENT = "REFRESH_EVENT",
}
